#!/bin/bash

#  This shell script directs data from the RPMsg device
#  to the alsa sound player.

#  Make a pipe.
#mkfifo soundfifo

#  The message echoed is not important, this serves
#  to initialize the communications mechanism from
#  ARM to PRU.
echo test > /dev/rpmsg_pru30

#  Direct the data to the fifo and put this process
#  in the background (&).
cat /dev/rpmsg_r30 > soundfifo &
#echo g > /dev/rpmsg_pru31
#  Play the data using the ALSA sound utility.
aplay -f S16_LE -Dplughw:1,0 soundfifo &

#  Use the character device connected to PRU1
#  to start the clock signal to PRU0.
#echo g > /dev/rpmsg_pru31

#  Sound should be heard from the speaker.

